import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const schoolNames = [
  "ACADEMIA CASA HOGAR SOR JUANA INÉS DE LA CRUZ A.C.",
  "PREPARATORIA CENTRO ESCOLAR CADEREYTA",
  "PREPA CEICKOR",
  "BACHILLERATO CARL ROGERS",
  "BACHILLERATO UGM QUERETARO",
  "BUCKINGHAM HIGH SCHOOL",
  "COLEGIO CASTELLANO PREPARATORIA",
  "COLEGIO CELTA INTERNACIONAL",
  "COLEGIO FONTANAR",
  "COLEGIO MILITARIZADO NUEVO MEXICO CAMPUS QUERETARO",
  "COLEGIO SOUTH HILL DE QUERETARO, S.C.",
  "COLEGIO WEXFORD",
  "HIGH SCHOOL JOHN DEWEY",
  "INSTITUTO ORIENTE QUERETARO",
  "INSTITUTO UNIVERSITARIO DE DESARROLLO HUMANO E INNOVACIÓN PROFESIONAL",
  "LA PROVIDENCIA. UNIVERSIDAD ANAHUAC QRO",
  "PREPA CAV",
  "PREPA PLENUS",
  "PREPARATORIA EMPRENDE INNOVA",
  "UNIVERSIDAD TEC MILENIO",
  "COLEGIO ALAMOS",
  "INSTITUTO ASUNCION DE QUERETARO",
  "CENTRO DE ESTUDIOS UNIVERSITARIOS DEL BAJIO PLANTEL QUERETARO",
  "CENTRO EDUCATIVO Y CULTURAL DEL ESTADO DE QUERETARO \"MANUEL GOMEZ MORIN\"",
  "COLEGIO DIEGO OLVERA",
  "COLEGIO FRAY LUIS DE LEON",
  "COLEGIO NUEVO CONTINENTE JURIQUILLA",
  "COLEGIO REALE",
  "COLEGIO SUISSE",
  "ESCUELA BANCARIA Y COMERCIAL CAMPUS QUERETARO",
  "HUMBOLDT SCHULE CAMPUS QUERETARO",
  "INSTITUTO ALBERT EINSTEIN",
  "INSTITUTO DE ESTUDIOS SUPERIORES DEL COLEGIO HOLANDES",
  "INSTITUTO THOMAS JEFFERSON CAMPUS QUERETARO",
  "JOHN F. KENNEDY",
  "JULES VERNE SCHOOL OF QUERETARO",
  "LICEO ESTUDIOS SUPERIORES",
  "PREPA ANAHUAC QUERETARO",
  "PREPARATORIA CUAUHTEMOC QUERETARO",
  "PREPARATORIA IBERO QUERETARO",
  "PREPARATORIA UNIVERSIDAD CUAUHTEMOC DE QUERETARO",
  "COLEGIO BOSTON",
  "COLEGIO NUEVO CONTINENTE",
  "INSTITUTO DE ESTUDIOS SUPERIORES DEL BAJÍO CAMPUS QUERÉTARO",
  "PREPARATORIA DEL VALLE DE MEXICO",
  "COLEGIO AUSTIN DE QUERETARO",
  "COLEGIO BILINGUE NEWLAND",
  "COLEGIO BOSTON QUERETARO",
  "COLEGIO BRITANICO",
  "COLEGIO CHAPULTEPEC DE QUERETARO",
  "COLEGIO DEL BOSQUE",
  "COLEGIO NEWLAND",
  "COLEGIO NICKEL",
  "COLEGIO VIKINGO",
  "ESCUELA MODERNA AMERICANA",
  "INSTITUTO ANGLO MODERNO",
  "INSTITUTO J F K",
  "INSTITUTO LAS AMERICAS DE QUERETARO",
  "J F K INTERNATIONAL SCHOOL",
  "JOHN F. KENNEDY SCHOOL",
  "LICEO MEXICANO CANADIENSE",
  "PREPARATORIA COLEGIO BOSTON",
  "COLEGIO BILBAO",
  "COLEGIO DE ESTUDIOS CIENTIFICOS Y TECNOLOGICOS ROBERT HOOKE",
  "COLEGIO ESTADOS UNIDOS DE AMERICA",
  "COLEGIO INGLES",
  "COLEGIO LIBRE DE ESTUDIOS UNIVERSITARIOS",
  "COLEGIO RIVERSIDE",
  "COLEGIO WASHINGTON",
  "INSTITUTO QUERETANO SAN JAVIER",
  "JULES VERNE",
  "PREPA UCO MONDRAGÓN",
  "COLEGIO DE BACHILLERES PLANTEL 19",
  "COLEGIO NUEVO MÉXICO JURIQUILLA",
  "INSTITUTO CUMBRES Y ALPES QUERÉTARO",
  "PREPARATORIA COLEGIO VERMONT",
  "UNIVERSIDAD DEL VALLE DE MÉXICO CAMPUS QUERÉTARO",
  "PREPARATORIA JOSÉ VASCONCELOS DE QUERETARO",
  "ADVANCE",
  "CENTRO EDUCATIVO KOALA",
  "COLEGIO ARCE",
  "COLEGIO DE BACHILLERES DEL ESTADO DE QUERÉTARO PLANTEL 15",
  "COLEGIO DIEGO OLVERA PLANTEL JURIQUILLA",
  "COLEGIO EL GATO CON BOTAS",
  "COLEGIO GEORGE BERNARD SHAW",
  "COLEGIO HELEN PARKHURST",
  "COLEGIO MONTREAL",
  "COLEGIO NUEVO HORIZONTE",
  "COLEGIO ONTARIO",
  "COLEGIO VERMONT",
  "CUMBRE 2000 COLEGIO",
  "ESCUELA PREPARATORIA PARTICULAR INCORPORADA A LA UAQ",
  "HUMBOLDT SCHULE",
  "INSTITUTO ASTURIANO",
  "INSTITUTO BILINGÜE ALMENA",
  "INSTITUTO PLANCARTE SC",
  "INSTITUTO TECNOLÓGICO DE ESTUDIOS SUPERIORES DE MONTERREY CAMPUS QUERÉTARO",
  "JULES VERNE SCHOOL",
  "LICEO EUROPEO",
  "LICEO JUVENIL CUMBRES",
  "PREPARATORIA BILBAO",
  "PREPARATORIA COLEGIO ALAMOS",
  "PREPARATORIA ICEP",
  "PREPARATORIA INSTITUTO THOMAS JEFFERSON",
  "UNIVERSIDAD DEL VALLE DE MÉXICO CAMPUS JURIQUILLA",
  "BACHILLERATO INSTITUTO HIDALGO",
  "COLEGIO ALBERT EINSTEIN",
  "COLEGIO CENTENARIO",
  "COLEGIO DEL SABER",
  "COLEGIO ESPAÑOL",
  "COLEGIO MARISTA",
  "COLÓN CENTER",
  "CONTINENTAL SCHOOL",
  "EMMANUEL CHRISTIAN SCHOOL",
  "ESCUELA JOHN DEWEY",
  "HARMONY SCHOOL",
  "INSTITUTO GASTRONOMICO DE ESTUDIOS SUPERIORES",
  "INSTITUTO LUX",
  "INSTITUTO PREUNIVERSITARIO DEL CENTRO DE QUERETARO",
  "INTERNATIONAL SCHOOL OF QUERÉTARO",
  "PREPA 360",
  "PREPARATORIA INTERNACIONAL DE QUERETARO",
  "PREPARATORIA VESPERTINA QUIROGA",
  "UNIVERSIDAD DE LONDRES",
  "VICTORIA SCHOOL",
  "VISION EDUCATIVA"
];

async function main() {
  console.log(`Starting upsert of ${schoolNames.length} schools...`);
  
  for (const name of schoolNames) {
    // We check if it exists by name (simplified for this migration)
    const existing = await prisma.school.findFirst({
      where: { name: name }
    });

    if (!existing) {
      await prisma.school.create({
        data: { name: name }
      });
      console.log(`Created: ${name}`);
    } else {
      console.log(`Skipped (already exists): ${name}`);
    }
  }
  
  console.log("Upsert complete!");
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
