import { NextRequest, NextResponse } from "next/server"
import { GoogleGenerativeAI } from "@google/generative-ai"
import { chatbotMessageSchema } from "@/validators/chatbot"

// Simple in-memory tracker (resets daily, resets on server restart).
let dailyAIRequests = 0
let lastResetDate = new Date().toDateString()

export async function POST(request: NextRequest) {
  try {
    const GEMINI_API_KEY = process.env.GEMINI_API_KEY
    const MAX_DAILY_REQUESTS = parseInt(process.env.MAX_AI_DAILY_REQUESTS || "500")
    
    const body = await request.json()
    
    // 1. Validation (Allow-listing & Length Limits)
    const validation = chatbotMessageSchema.safeParse(body)
    
    if (!validation.success) {
      return NextResponse.json({ 
        error: "Entrada inválida", 
        details: validation.error.issues[0]?.message 
      }, { status: 400 })
    }

    const {
      message,
      conversationHistory = [],
      userName = "Estudiante",
      xp = 0,
      level = 1,
      currentPath = ""
    } = validation.data

    // Context analysis
    let contextDescription = ""
    if (currentPath?.includes('/learn/')) {
      const parts = currentPath.split('/').filter(Boolean)
      const topicId = parts[1] // tema-01, tema-02...
      const lessonSlug = parts[parts.length - 1] === 'interactive' ? parts[parts.length - 2] : parts[parts.length - 1]

      const topicNum = topicId?.replace('tema-', '')
      const lessonTitle = lessonSlug?.replace(/-/g, ' ')

      contextDescription = `\nCONTEXTO ACTUAL: El usuario está en la lección "${lessonTitle}" del Tema ${topicNum}.`
    } else if (currentPath?.includes('/courses')) {
      contextDescription = `\nCONTEXTO ACTUAL: El usuario está explorando el catálogo de cursos.`
    }

    const userStats = `\nESTADÍSTICAS DEL USUARIO: XP: ${xp}, Nivel: ${level}.`

    if (!GEMINI_API_KEY) {
      return NextResponse.json(
        { response: "Billy está temporalmente fuera de línea. Por favor, intenta más tarde." },
        { status: 200 }
      )
    }

    // Check limit
    const currentDate = new Date().toDateString()
    if (currentDate !== lastResetDate) {
      dailyAIRequests = 0
      lastResetDate = currentDate
    }

    if (dailyAIRequests >= MAX_DAILY_REQUESTS) {
      return NextResponse.json({
        response: "Billy ha tenido un día muy ocupado ayudando a otros. Vuelve mañana para seguir aprendiendo juntos.",
        source: "limit-reached"
      })
    }

    const systemPrompt = `Eres Billy, el mentor asistente de BIZEN. BIZEN enseña educación financiera a jóvenes.
ESTÁS HABLANDO CON: ${userName}. Dirígete a esta persona por su nombre de forma natural pero NO LO SALUDES EN CADA MENSAJE, ve directo al grano.${userStats}${contextDescription}

PERSONALIDAD:
- Eres relajado, profesional, entusiasta y educado.
- Tienes un tono moderno y amigable pero SIN usar modismos excesivos, jerga informal o palabras altisonantes.
- ESTÁ ESTRICTAMENTE PROHIBIDO usar palabras como "wey", "neta", o cualquier tipo de lenguaje vulgar o excesivamente informal.
- NO USES EMOJIS: Tienes prohibido usar emojis en tus respuestas. Mantén el texto limpio.

REGLAS DE INTERACCIÓN Y FORMATO:
- DIRECTO AL GRANO: NUNCA saludes al inicio de tu respuesta (sin "¡Hola!", "¡Qué tal!", etc.). Responde directamente lo que se pregunta.
- SÉ CONCISO Y CLARO: Tus respuestas deben ser directas. No des información de sobra ni repitas lo que el usuario ya sabe. Usa 1 o 2 párrafos cortos como máximo.
- Evita los bloques masivos de texto. Si hay mucha información, resume a los puntos clave usando viñetas.

LO QUE HACES:
1. EDUCACIÓN: Explica conceptos pero NO des asesoría financiera real. Sé un guía que motiva.
2. CONTEXTO BIZEN: Conoces los temas de Identidad Digital, Finanzas Personales, Presupuesto, Inversiones, Emprendimiento y Bienestar.
3. SOPORTE: Problemas técnicos a soporte@bizen.mx.

RECUERDA: Tu objetivo es que el usuario aprenda sin aburrirse. Sé muy claro, moderno y motivador. NO USES EMOJIS y VE DIRECTO AL GRANO sin saludar en cada mensaje.`

    const genAI = new GoogleGenerativeAI(GEMINI_API_KEY)
    const geminiModel = genAI.getGenerativeModel({
      model: "gemini-1.5-flash" 
    })

    const formattedHistory = (conversationHistory || [])
      .map((h: any) => `${h.role === 'user' ? 'USUARIO' : 'BILLY'}: ${h.content}`)
      .join('\n');

    const fullPromptForAI = `SISTEMA: ${systemPrompt}\n\nHISTORIAL PREVIO:\n${formattedHistory}\n\nMENSAJE ACTUAL DEL USUARIO: ${message}`

    const result = await geminiModel.generateContent(fullPromptForAI)
    const response = await result.response
    
    // Safety check for candidates
    if (!response || !response.candidates || response.candidates.length === 0) {
      console.error("❌ [Billy:NoCandidates]:", JSON.stringify(response))
      throw new Error("No response generated by AI (potentially blocked)")
    }

    let responseText = ""
    try {
      responseText = response.text()
    } catch (e) {
      console.warn("⚠️ [Billy:TextMethodFailed]: Attempting manual extraction", e)
      const candidate = response.candidates[0]
      if (candidate?.content?.parts?.[0]?.text) {
        responseText = candidate.content.parts[0].text
      } else {
        throw new Error("Could not extract text from AI response")
      }
    }

    dailyAIRequests++

    return NextResponse.json({
      response: responseText.trim(),
      source: "google:gemini-1.5-flash"
    })

  } catch (error: any) {
    console.error("❌ [Billy:BackendError]:", error)
    // Return the specific error for debugging
    return NextResponse.json(
      { 
        response: `¡Ups! Billy está descansando un momento (${error.message || "Error desconocido"}). ¿Puedes intentarlo de nuevo?`,
        debug: error.message 
      },
      { status: 200 }
    )
  }
}

export async function OPTIONS() {
  return new NextResponse(null, {
    status: 200,
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "POST, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type"
    }
  })
}
