import { NextResponse } from 'next/server';

export async function GET(req: Request) {
  const { searchParams } = new URL(req.url);
  const symbol = searchParams.get('symbol');

  const ALL_NEWS = [
    {
      id: 1,
      symbol: "MARKET",
      author: "Bloomberg News",
      source: "Bloomberg",
      title: "Mercados globales en alerta tras discurso de Trump sobre conflicto en Irán",
      category: "Macroeconomía",
      time: "Hace 1 hora",
      image: "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&w=800&q=80",
      url: "https://www.bloomberg.com/markets",
      desc: "La volatilidad se dispara en Wall Street tras advertencias de nuevas represalias en Medio Oriente.",
      fullDesc: "Los principales índices de Estados Unidos experimentaron una sesión de alta volatilidad después de que el presidente Trump sugiriera un endurecimiento de las acciones militares en Irán. Aunque los mercados recuperaron parte de sus pérdidas iniciales, el sentimiento de precaución prevalece entre los inversores internacionales, quienes ahora monitorean de cerca los próximos pasos diplomáticos."
    },
    {
      id: 2,
      symbol: "OIL",
      author: "Reuters Commodities",
      source: "Reuters",
      title: "Petróleo WTI supera los $110 dólares ante temor por suministro global",
      category: "Energía",
      time: "Hace 3 horas",
      image: "https://images.unsplash.com/photo-1518175006663-1e90b410cda6?auto=format&fit=crop&w=800&q=80",
      url: "https://www.reuters.com/business/energy/",
      desc: "El crudo alcanza máximos locales mientras las tensiones geopolíticas amenazan las rutas de exportación.",
      fullDesc: "Los precios del petróleo West Texas Intermediate (WTI) y Brent han registrado un repunte significativo, rompiendo barreras psicológicas clave. La incertidumbre sobre la estabilidad en el Golfo Pérsico ha llevado a los analistas a revisar al alza sus proyecciones de precios para el trimestre, lo que añade presión a las expectativas de inflación global."
    },
    {
      id: 3,
      symbol: "ECON",
      author: "CNBC Business",
      source: "CNBC",
      title: "Solicitudes de desempleo caen a 202,000 en EE.UU., superando expectativas",
      category: "Economía",
      time: "Hace 5 horas",
      image: "https://images.unsplash.com/photo-1543286386-2e659306cd6c?auto=format&fit=crop&w=800&q=80",
      url: "https://www.cnbc.com/economy/",
      desc: "El mercado laboral estadounidense muestra una resiliencia inesperada a pesar de las altas tasas de interés.",
      fullDesc: "Los nuevos datos de solicitudes semanales por desempleo revelan que el mercado laboral sigue siendo robusto. Con una cifra menor a la proyectada por los economistas (215,000), la Reserva Federal se enfrenta a un desafío complejo: una economía que no parece enfriarse lo suficiente como para justificar recortes inmediatos en las tasas de interés."
    },
    {
      id: 4,
      symbol: "FED",
      author: "Federal Reserve Watch",
      source: "Yahoo Finance",
      title: "Dudas sobre el 'aterrizaje suave' tras datos manufactureros de ISM",
      category: "Bancos",
      time: "Hace 8 horas",
      image: "https://images.unsplash.com/photo-1501167786227-4cba60f6d58f?auto=format&fit=crop&w=800&q=80",
      url: "https://finance.yahoo.com/news/",
      desc: "El aumento en los precios pagados por los fabricantes sugiere una inflación más persistente de lo esperado.",
      fullDesc: "El índice PMI manufacturero del ISM mostró recientemente que los precios pagados por las empresas están volviendo a subir. Esta señal indica que la inflación subyacente puede tardar más en bajar del 3%, complicando el objetivo del 2% de la Fed y forzando a los inversores a revaluar su exposición a activos de riesgo."
    },
    {
      id: 5,
      symbol: "TICKER",
      author: "Market Beat",
      source: "Financial Times",
      title: "Aerolíneas bajo presión: United y Carnival lideran caídas por combustible",
      category: "Transporte",
      time: "Hace 10 horas",
      image: "https://images.unsplash.com/photo-1436491865332-7a61a109c0f3?auto=format&fit=crop&w=800&q=80",
      url: "https://www.ft.com/markets",
      desc: "El encarecimiento del combustible de aviación afecta los márgenes proyectados para la temporada de verano.",
      fullDesc: "El sector transporte y viajes se ha visto afectado por el reciente aumento en los precios de la energía. United Airlines y Carnival han visto retrocesos significativos en sus cotizaciones ante el temor de que los altos costos operativos y la inflación al consumidor reduzcan la demanda de viajes en los próximos meses."
    },
    {
      id: 6,
      symbol: "XOM",
      author: "Energy Analysts",
      source: "OilPrice.com",
      title: "Exxon y Chevron ganan terreno ante alza en márgenes de refinamiento",
      category: "Inversión",
      time: "Hace 12 horas",
      image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80",
      url: "https://oilprice.com/",
      desc: "Las grandes petroleras se benefician del entorno de precios altos y demanda sostenida.",
      fullDesc: "Mientras otros sectores sufren, las empresas energéticas tradicionales como Exxon Mobil y Chevron están capturando flujos de capital. La combinación de precios de crudo elevados y una mejora en los márgenes de refinamiento ha posicionado a estos activos como un refugio de valor en una cartera diversificada durante tiempos de inestabilidad geopolítica."
    },
    {
      id: 7,
      symbol: "GOLD",
      author: "Metals Specialist",
      source: "Kitco News",
      title: "El Oro se mantiene firme arriba de los $2,250 como refugio",
      category: "Commodities",
      time: "Hace 15 horas",
      image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80",
      url: "https://www.kitco.com/news/",
      desc: "La demanda física y central de oro sigue rompiendo récords históricos este mes.",
      fullDesc: "El oro continúa su racha alcista, sirviendo como el guardián de valor por excelencia ante la volatilidad de las divisas y la incertidumbre en Medio Oriente. Los bancos centrales de los mercados emergentes siguen acumulando reservas físicas, lo que proporciona un piso sólido al precio del metal precioso a pesar de un dólar relativamente fuerte."
    },
    {
      id: 8,
      symbol: "TECH",
      author: "Tech Insider",
      source: "The Verge",
      title: "Apple explora robótica tras fin de proyecto de auto eléctrico",
      category: "Tecnología",
      time: "Hace 18 horas",
      image: "https://images.unsplash.com/photo-1485738422979-f5c462d49f74?auto=format&fit=crop&w=800&q=80",
      url: "https://www.theverge.com/apple",
      desc: "La compañía busca su próximo gran éxito en la robótica doméstica y la IA integrada.",
      fullDesc: "Tras cancelar su ambicioso proyecto de vehículo autónomo, Apple está redirigiendo sus recursos de ingeniería hacia la robótica personal. Los informes sugieren que están trabajando en dispositivos capaces de moverse en el hogar y mejorar la interacción de los usuarios con el ecosistema de Apple mediante IA avanzada."
    },
    {
      id: 9,
      symbol: "MXN",
      author: "LatAm Analyst",
      source: "El Financiero",
      title: "Súper Peso resiste: MXN se mantiene sólido a pesar del ruido global",
      category: "Divisas",
      time: "Hace 20 horas",
      image: "https://images.unsplash.com/photo-1518458022751-0a53d3f96603?auto=format&fit=crop&w=800&q=80",
      url: "https://www.elfinanciero.com.mx/markets/",
      desc: "El atractivo diferencial de tasas sigue atrayendo flujos hacia la moneda mexicana.",
      fullDesc: "El peso mexicano sigue demostrando por qué ha sido una de las monedas más fuertes frente al dólar. Aunque la volatilidad externa ha aumentado, el carry trade y la llegada de inversión por nearshoring mantienen la paridad cambiaria en niveles históricamente bajos para el último periodo."
    },
    {
      id: 10,
      symbol: "NVDA",
      author: "Silicon Valley Correspondent",
      source: "TechCrunch",
      title: "Nvidia amplía su ventaja en chips de IA con nueva arquitectura",
      category: "Hardware",
      time: "Hace 22 horas",
      image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80",
      url: "https://techcrunch.com/tag/nvidia/",
      desc: "La demanda institucional de infraestructura para modelos de lenguaje masivos no muestra signos de pausa.",
      fullDesc: "Nvidia continúa su ascenso meteórico al presentar mejoras en su arquitectura de centro de datos. Con el ecosistema de IA generativa expandiéndose hacia sectores industriales y de salud, los pedidos de sus aceleradores de hardware se han extendido hasta finales del próximo año fiscal, consolidando su posición como el motor de la revolución tecnológica actual."
    },
    {
      id: 11,
      symbol: "BTC",
      author: "Crypto Pioneer",
      source: "CoinDesk",
      title: "Bitcoin rompe récord histórico superando los $100,000",
      category: "Cripto",
      time: "Hace 1 hora",
      image: "https://images.unsplash.com/photo-1518546305927-5a555bb7020d?auto=format&fit=crop&w=800&q=80",
      url: "https://www.coindesk.com",
      desc: "La adopción masiva por parte de instituciones financieras impulsa el precio a niveles nunca antes vistos.",
      fullDesc: "Bitcoin ha cruzado la barrera psicológica de los seis dígitos, marcando un hito en la historia de las finanzas digitales. Analistas sugieren que la entrada de fondos soberanos al mercado ha sido el catalizador definitivo para este rally sin precedentes."
    },
    {
      id: 12,
      symbol: "TSLA",
      author: "Auto Industry Analyst",
      source: "Forbes",
      title: "Tesla presenta su modelo compacto de $25,000 para mercados globales",
      category: "Movilidad",
      time: "Hace 4 horas",
      image: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=800&q=80",
      url: "https://www.forbes.com/business/",
      desc: "El vehículo busca democratizar la movilidad eléctrica y competir en el mercado masivo.",
      fullDesc: "Con un enfoque en la eficiencia de manufactura y nuevas celdas de batería, Tesla promete revolucionar el segmento de entrada. El anuncio ha disparado las acciones de la compañía un 8% en las operaciones después del cierre."
    },
    {
      id: 13,
      symbol: "SPACE",
      author: "Aerospace Weekly",
      source: "SpaceNews",
      title: "SpaceX completa con éxito la primera misión comercial a Marte",
      category: "Espacio",
      time: "Hace 6 horas",
      image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80",
      url: "https://spacenews.com",
      desc: "La Starship logra aterrizar suministros críticos para la futura base habitada.",
      fullDesc: "Este logro marca el inicio de la era multiplanetaria. La misión no solo probó la tecnología de reentrada atmosférica marciana, sino que también estableció los protocolos de comunicación de banda ancha entre planetas."
    },
    {
      id: 14,
      symbol: "VC",
      author: "Silicon Insider",
      source: "TechCrunch",
      title: "Inversión en Startups de IA supera los $50B en el primer trimestre",
      category: "Capital",
      time: "Hace 9 horas",
      image: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&w=800&q=80",
      url: "https://techcrunch.com/category/startups/",
      desc: "El capital de riesgo se concentra en modelos de lenguaje masivos y robótica aplicada.",
      fullDesc: "A pesar del enfriamiento en otros sectores tecnológicos, la IA generativa sigue atrayendo flujos récord. Los grandes fondos están duplicando sus apuestas en infraestructura crítica y aplicaciones B2B especializadas."
    },
    {
      id: 15,
      symbol: "REALESTATE",
      author: "PropTech Reporter",
      source: "Wall Street Journal",
      title: "Mercado inmobiliario en Miami reporta auge por relocalización tecnológica",
      category: "Bienes Raíces",
      time: "Hace 12 horas",
      image: "https://images.unsplash.com/photo-1460317442991-0ec239397118?auto=format&fit=crop&w=800&q=80",
      url: "https://www.wsj.com/real-estate",
      desc: "Las oficinas de lujo alcanzan niveles de ocupación récord en el centro de la ciudad.",
      fullDesc: "La tendencia de migración corporativa hacia estados con menores impuestos sigue impulsando la demanda. Los precios por metro cuadrado han subido un 15% anual, sin señales de desaceleración en el corto plazo."
    },
    {
      id: 16,
      symbol: "CHIPS",
      author: "Semiconductor Watch",
      source: "Nikkei Asia",
      title: "TSMC acelera producción de chips de 2nm ante demanda de IA",
      category: "Tecnología",
      time: "Hace 14 horas",
      image: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
      url: "https://asia.nikkei.com/Business/Tech/Semiconductors",
      desc: "La nueva arquitectura promete una eficiencia energética 30% superior a la generación actual.",
      fullDesc: "El fabricante de chips más grande del mundo está invirtiendo miles de millones en nuevas plantas para asegurar la cadena de suministro global. Los analistas prevén que esta tecnología sea la base de los smartphones y servidores del 2026."
    },
    {
      id: 17,
      symbol: "SUSTAIN",
      author: "Eco Finance",
      source: "The Guardian",
      title: "Inversión en energías renovables supera a los fósiles por primera vez",
      category: "Energía",
      time: "Hace 18 horas",
      image: "https://images.unsplash.com/photo-1466611653911-954815391f27?auto=format&fit=crop&w=800&q=80",
      url: "https://www.theguardian.com/business/renewable-energy",
      desc: "El costo nivelado de la energía solar y eólica sigue cayendo globalmente.",
      fullDesc: "Un reporte global confirma que el capital institucional ahora prefiere proyectos verdes debido a su mayor previsibilidad y cumplimiento de criterios ESG. Este cambio tectónico redefine el futuro del sector energético europeo y americano."
    },
    {
      id: 18,
      symbol: "EUR",
      author: "Macro Monitor",
      source: "Eurozone Review",
      title: "El Euro se fortalece ante señales de baja inflación en Alemania",
      category: "Divisas",
      time: "Hace 20 horas",
      image: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&w=800&q=80",
      url: "https://www.reuters.com/markets/currencies/",
      desc: "Los mercados descuentan un posible recorte de tasas por el BCE en junio.",
      fullDesc: "La divisa común europea ha mostrado una resiliencia notable. A pesar de los desafíos industriales, los datos macroeconómicos sugieren que la zona euro podría evitar una recesión técnica este año."
    },
    {
      id: 19,
      symbol: "SHOP",
      author: "Retail Trends",
      source: "Business Insider",
      title: "Amazon integra drones para entregas en menos de 15 minutos en Texas",
      category: "Logística",
      time: "Hace 22 horas",
      image: "https://images.unsplash.com/photo-1521898284481-a5ec3ad18c72?auto=format&fit=crop&w=800&q=80",
      url: "https://www.businessinsider.com/amazon-prime-air",
      desc: "El servicio Prime Air comienza su fase de expansión comercial masiva.",
      fullDesc: "Mediante el uso de algoritmos de navegación avanzada, Amazon logra sortear obstáculos urbanos y entregar paquetes ligeros casi instantáneamente. Este avance promete cambiar las expectativas de consumo en las zonas suburbanas."
    },
    {
      id: 20,
      symbol: "HEALTH",
      author: "BioTech Analyst",
      source: "STAT News",
      title: "Nueva terapia génica muestra remisión del 100% en pruebas iniciales",
      category: "Salud",
      time: "Hace 23 horas",
      image: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=80",
      url: "https://www.statnews.com",
      desc: "El tratamiento enfocado en enfermedades raras podría recibir aprobación acelerada.",
      fullDesc: "Los resultados clínicos han superado todas las expectativas de la FDA. El precio de las acciones de la biotecnológica responsable se ha duplicado en una sola jornada, impulsando el sector salud en el Nasdaq."
    },
    {
      id: 21,
      symbol: "MX",
      author: "Economía Local",
      source: "El Economista",
      title: "Inflación en México liga su cuarta quincena a la baja: 4.42%",
      category: "Macroeconomía",
      time: "Hace 2 horas",
      image: "https://images.unsplash.com/photo-1585468202523-289ba100c619?auto=format&fit=crop&w=800&q=80",
      url: "https://www.eleconomista.com.mx/",
      desc: "Los datos del INEGI sugieren una posible pausa en el endurecimiento del Banco de México.",
      fullDesc: "La inflación general en México continúa su tendencia descendente, superando levemente las expectativas de los analistas. Este enfriamiento de los precios abre la puerta a que Banxico considere un recorte en la tasa de referencia en las próximas reuniones de política monetaria."
    },
    {
      id: 22,
      symbol: "AI",
      author: "Future Tech",
      source: "Ars Technica",
      title: "OpenAI presenta 'Sora' en versión beta para creadores seleccionados",
      category: "Inteligencia Artificial",
      time: "Hace 5 horas",
      image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=800&q=80",
      url: "https://arstechnica.com/",
      desc: "El modelo de generación de video a partir de texto sorprende por su realismo cinematográfico.",
      fullDesc: "Sora permite crear escenas complejas con múltiples personajes y movimientos de cámara precisos. Aunque aún no está disponible para el público general, los primeros resultados han generado un intenso debate sobre el futuro de la producción audiovisual y la propiedad intelectual."
    },
    {
      id: 23,
      symbol: "SPX",
      author: "Wall St. Reporter",
      source: "Investing.com",
      title: "S&P 500 alcanza nuevo máximo gracias al rally de semiconductores",
      category: "Acciones",
      time: "Hace 7 horas",
      image: "https://images.unsplash.com/photo-1611974717482-48a5c18dc907?auto=format&fit=crop&w=800&q=80",
      url: "https://www.investing.com/indices/us-spx-500",
      desc: "El optimismo corporativo ignora las señales de cautela de la Reserva Federal.",
      fullDesc: "A pesar de las tasas de interés históricamente altas, el sector tecnológico sigue impulsando al mercado. Las empresas ligadas a la infraestructura de red y el hardware de IA están captando la mayor parte de las entradas de capital este trimestre."
    },
    {
      id: 24,
      symbol: "ETH",
      author: "DeFi Insider",
      source: "The Block",
      title: "Ethereum completa con éxito la actualización 'Dencun'",
      category: "Cripto",
      time: "Hace 10 horas",
      image: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&w=800&q=80",
      url: "https://www.theblock.co/",
      desc: "Las tarifas en las soluciones de Capa 2 (L2) caen drásticamente tras la implementación de blobs.",
      fullDesc: "La esperada actualización Dencun introduce el proto-danksharding, reduciendo las barreras de costo para los usuarios finales. Los analistas prevén un aumento masivo en la actividad de dApps y juegos Web3 en los próximos meses."
    },
    {
      id: 25,
      symbol: "BANK",
      author: "Financial Review",
      source: "The Financial Times",
      title: "Bancos centrales exploran el uso de CBDC para pagos transfronterizos",
      category: "Banca Central",
      time: "Hace 12 horas",
      image: "https://images.unsplash.com/photo-1550565118-3a14e8d0386f?auto=format&fit=crop&w=800&q=80",
      url: "https://www.ft.com/",
      desc: "El proyecto busca reducir los tiempos de liquidación de días a segundos.",
      fullDesc: "Las Monedas Digitales de Banco Central (CBDC) están pasando de la teoría a la práctica. Con el fin de modernizar el sistema SWIFT, varias instituciones globales están colaborando en una infraestructura blockchain compartida."
    },
    {
      id: 26,
      symbol: "AMZN",
      author: "E-commerce Watch",
      source: "Retail Insider",
      title: "Amazon reporta ahorros masivos tras integrar IA en su logística de última milla",
      category: "Logística",
      time: "Hace 14 horas",
      image: "https://images.unsplash.com/photo-1521191761617-695617cb9932?auto=format&fit=crop&w=800&q=80",
      url: "https://www.businessinsider.com/",
      desc: "La optimización de rutas mediante algoritmos predictivos reduce costos operativos en un 15%.",
      fullDesc: "Amazon ha logrado mejorar la puntualidad de sus entregas reduciendo al mismo tiempo las emisiones de carbono. La empresa planea expandir esta tecnología a sus mercados internacionales antes de finalizar el año."
    },
    {
      id: 27,
      symbol: "NEARSHORING",
      author: "Trade Weekly",
      source: "El Financiero",
      title: "Inversión en parques industriales en el norte de México sube 25%",
      category: "Inmobiliario",
      time: "Hace 16 horas",
      image: "https://images.unsplash.com/photo-1504307651254-35682fd93502?auto=format&fit=crop&w=800&q=80",
      url: "https://www.elfinanciero.com.mx/",
      desc: "La relocalización de cadenas de suministro chinas impulsa la construcción en Nuevo León y Coahuila.",
      fullDesc: "El fenómeno del Nearshoring está transformando el paisaje industrial de México. Con la llegada de gigantes tecnológicos y automotrices, la demanda de naves industriales de última generación ha alcanzado un máximo histórico."
    },
    {
      id: 28,
      symbol: "ESTAFA",
      author: "Security Alerts",
      source: "CONDUSEF",
      title: "Alertan sobre nuevas estafas de inversión vía redes sociales en México",
      category: "Seguridad",
      time: "Hace 19 horas",
      image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80",
      url: "https://www.condusef.gob.mx/",
      desc: "Esquemas ponzi disfrazados de trading de IA están afectando a miles de jóvenes.",
      fullDesc: "La CONDUSEF advierte sobre plataformas que prometen rendimientos 'garantizados' e irreales. Se recomienda verificar que cualquier entidad financiera esté debidamente registrada y regulada antes de depositar fondos."
    },
    {
      id: 29,
      symbol: "GOLD",
      author: "Commodity Watch",
      source: "Kitco News",
      title: "Bancos centrales de Asia aumentan sus reservas de oro físico",
      category: "Metas Preciosos",
      time: "Hace 21 horas",
      image: "https://images.unsplash.com/photo-1610375461246-83df85028421?auto=format&fit=crop&w=800&q=80",
      url: "https://www.kitco.com/",
      desc: "La diversificación de reservas lejos del dólar sostiene los precios en máximos anuales.",
      fullDesc: "A pesar de la fortaleza del dólar, el oro sigue siendo el activo preferido por los bancos centrales para proteger sus reservas. China e India lideran la compra física, impulsando el precio por encima de resistencias técnicas clave."
    },
    {
      id: 30,
      symbol: "EV",
      author: "Auto Future",
      source: "Electrek",
      title: "Baterías de estado sólido: Toyota promete autonomía de 1,200km para 2027",
      category: "Automotriz",
      time: "Hace 23 horas",
      image: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&w=800&q=80",
      url: "https://electrek.co/",
      desc: "La tecnología revolucionaria reduciría el tiempo de carga a tan solo 10 minutos.",
      fullDesc: "El anuncio de Toyota marca un punto de inflexión en la carrera por el vehículo eléctrico. Las baterías de estado sólido ofrecen mayor densidad energética y seguridad, eliminando la ansiedad por el rango de autonomía existente hoy."
    },
    {
      id: 31,
      symbol: "AAPL",
      author: "Tech Corner",
      source: "MacRumors",
      title: "Expectativas altas por iOS 18: La IA será el centro de la actualización",
      category: "Tecnología",
      time: "Hace 1 día",
      image: "https://images.unsplash.com/photo-1510557883984-3cfb16027f6a?auto=format&fit=crop&w=800&q=80",
      url: "https://www.macrumors.com/",
      desc: "Apple integraría modelos de lenguaje en Siri y Safari para competir con Google.",
      fullDesc: "Se espera que la próxima conferencia de desarrolladores de Apple revele cómo la compañía planea integrar la IA generativa de forma privada en el hardware del iPhone, renovando por completo la experiencia de usuario."
    },
    {
      id: 32,
      symbol: "META",
      author: "Venture Beat",
      source: "TechCrunch",
      title: "Meta lanza 'Llama 4': El modelo de código abierto más potente hasta la fecha",
      category: "SaaS",
      time: "Hace 1 día",
      image: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?auto=format&fit=crop&w=800&q=80",
      url: "https://techcrunch.com/",
      desc: "Mark Zuckerberg reafirma su apuesta por democratizar el acceso a la inteligencia artificial.",
      fullDesc: "Llama 4 promete una eficiencia superior y capacidades de razonamiento lógico que rivalizan con modelos de pago. Esta jugada busca posicionar a Meta como el estándar de la industria para desarrolladores independientes."
    },
    {
      id: 33,
      symbol: "MXN",
      author: "Finanzas MX",
      source: "El Financiero",
      title: "Remesas a México alcanzan cifra récord de $63 mil millones de dólares",
      category: "Divisas",
      time: "Hace 1 día",
      image: "https://images.unsplash.com/photo-1593642532400-2682810df593?auto=format&fit=crop&w=800&q=80",
      url: "https://www.elfinanciero.com.mx/",
      desc: "El flujo de dólares sigue siendo un pilar fundamental para el consumo interno mexicano.",
      fullDesc: "A pesar de la fortaleza del peso, el volumen de remesas sigue creciendo. Estos flujos de capital ayudan a mantener la estabilidad de la balanza de pagos y apoyan a millones de familias en sectores rurales."
    },
    {
      id: 34,
      symbol: "STOCKS",
      author: "Market Watch",
      source: "CNBC",
      title: "Estrategias de inversión 2026: Por qué los ETFs de dividendos están de moda",
      category: "Inversión",
      time: "Hace 2 días",
      image: "https://images.unsplash.com/photo-1535320903710-d993d3d77d29?auto=format&fit=crop&w=800&q=80",
      url: "https://www.cnbc.com/",
      desc: "Los inversores buscan ingresos pasivos ante la incertidumbre de crecimiento en las grandes tecnológicas.",
      fullDesc: "Los fondos cotizados (ETFs) que se enfocan en empresas con historiales de dividendos crecientes han visto entradas récord. Esta rotación defensiva busca capitalizar la estabilidad en un entorno de alta volatilidad."
    },
    {
      id: 35,
      symbol: "ENERGY",
      author: "Green World",
      source: "Reuters",
      title: "Fusión nuclear: startup europea logra mantener plasma por tiempo récord",
      category: "Energía",
      time: "Hace 2 días",
      image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80",
      url: "https://www.reuters.com/",
      desc: "El avance acerca a la humanidad a una fuente de energía limpia ilimitada.",
      fullDesc: "Aunque todavía nos separan años de la comercialización, este experimento demuestra que el control magnético del plasma es viable a gran escala. La inversión privada en startups de fusión ha crecido un 40% este año."
    },
    {
      id: 36,
      symbol: "FOOD",
      author: "Global Trends",
      source: "The Economist",
      title: "Crisis de fertilizantes: Agricultores buscan alternativas orgánicas para bajar costos",
      category: "Agricultura",
      time: "Hace 2 días",
      image: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=800&q=80",
      url: "https://www.economist.com/",
      desc: "El aumento en el precio del gas natural impacta directamente en la producción de alimentos.",
      fullDesc: "La dependencia de importaciones de potasio y nitrógeno está forzando a una revolución verde accidental. Los fertilizantes biotecnológicos están ganando terreno como una solución sostenible y económica de largo plazo."
    },
    {
      id: 37,
      symbol: "TRAVEL",
      author: "Vacation Pro",
      source: "Skift",
      title: "Turismo de lujo en Baja California registra su mejor temporada histórica",
      category: "Servicios",
      time: "Hace 3 días",
      image: "https://images.unsplash.com/photo-1512411030491-b3b0d2d38626?auto=format&fit=crop&w=800&q=80",
      url: "https://skift.com/",
      desc: "Los Cabos y La Paz se consolidan como destinos preferidos para el trabajo remoto de alta gama.",
      fullDesc: "La infraestructura hotelera de ultra-lujo en la región ha atraído a nómadas digitales de alto perfil. El gasto promedio por turista ha subido un 30% respecto a los niveles pre-pandemia."
    },
    {
      id: 38,
      symbol: "EDU",
      author: "Learning Today",
      source: "Forbes",
      title: "EdTech: El micro-aprendizaje conquista el mercado corporativo",
      category: "Educación",
      time: "Hace 3 días",
      image: "https://images.unsplash.com/photo-1501504905953-f83136739947?auto=format&fit=crop&w=800&q=80",
      url: "https://www.forbes.com/",
      desc: "Cápsulas de conocimiento de 5 minutos reemplazan a los cursos extensos por su alta retención.",
      fullDesc: "Las empresas están adoptando plataformas de aprendizaje ágil similares a TikTok pero enfocadas en habilidades profesionales. BIZEN es citada como uno de los ejemplos de éxito en este nuevo paradigma educativo."
    },
    {
      id: 39,
      symbol: "STARTUP",
      author: "Founder Stories",
      source: "Wired",
      title: "La era de la eficiencia: Startups priorizan el flujo de caja sobre el crecimiento",
      category: "Negocios",
      time: "Hace 4 días",
      image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80",
      url: "https://www.wired.com/",
      desc: "El fin del dinero fácil obliga a los fundadores a buscar la rentabilidad desde el primer día.",
      fullDesc: "Ya no basta con tener una gran idea y quemar dinero. Los fondos de Silicon Valley ahora exigen modelos de negocio probados y márgenes brutos saludables antes de otorgar rondas de serie A."
    },
    {
      id: 40,
      symbol: "HEALTH",
      author: "Wellness Report",
      source: "BBC News",
      title: "Senolíticos: El fármaco que 'limpia' células viejas entra en fase final de estudio",
      category: "Ciencia",
      time: "Hace 4 días",
      image: "https://images.unsplash.com/photo-1532187863486-abf9d3445de4?auto=format&fit=crop&w=800&q=80",
      url: "https://www.bbc.com/news",
      desc: "La ciencia de la longevidad promete retrasar significativamente las enfermedades del envejecimiento.",
      fullDesc: "Expertos en biotecnología sugieren que estamos cerca de poder prevenir la degeneración celular. Si las pruebas clínicas confirman su seguridad, este fármaco podría revolucionar los sistemas de salud pública mundiales."
    },
    {
      id: 41,
      symbol: "MERCADO",
      author: "BIZEN News",
      source: "BIZEN",
      title: "Cómo navegar un mercado bajista sin entrar en pánico",
      category: "Educación",
      time: "Hace 5 días",
      image: "https://images.unsplash.com/photo-1518186285589-2f7649de83e0?auto=format&fit=crop&w=800&q=80",
      url: "#",
      desc: "Guía práctica para proteger tu capital cuando las gráficas están rojas.",
      fullDesc: "El equipo educativo de BIZEN publica una guía detallada sobre psicología del inversor. Aprender a diferenciar entre un ajuste sano y un cambio de tendencia es vital para cualquier inversor joven que quiera construir riqueza real."
    },
    {
      id: 42,
      symbol: "TECH",
      author: "Gadget Central",
      source: "Gizmodo",
      title: "Buscadores web: ChatGPT Search amenaza el reinado histórico de Google",
      category: "Internet",
      time: "Hace 5 días",
      image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&w=800&q=80",
      url: "https://gizmodo.com/",
      desc: "La respuesta directa desplaza al formato de lista de enlaces tradicional.",
      fullDesc: "La competencia en el sector de las búsquedas se intensifica. Google ha respondido integrando resúmenes generativos en su página principal, pero los usuarios más jóvenes parecen preferir interfaces de chat conversacional."
    },
    {
      id: 43,
      symbol: "CRIPTO",
      author: "Crypto Weekly",
      source: "Bitcoin Magazine",
      title: "Minería de Bitcoin en México: El potencial de la energía geotérmica",
      category: "Innovación",
      time: "Hace 6 días",
      image: "https://images.unsplash.com/photo-1621416848440-2369dadae357?auto=format&fit=crop&w=800&q=80",
      url: "https://bitcoinmagazine.com/",
      desc: "Proyectos en el centro del país buscan usar el exceso de vapor volcánico para generar BTC.",
      fullDesc: "Varios emprendedores están explorando asociaciones con empresas de energía limpia para descentralizar la minería. México podría convertirse en un hub regional para la minería verde gracias a sus recursos naturales únicos."
    },
    {
      id: 44,
      symbol: "ECON",
      author: "Global Observer",
      source: "Al Jazeera Finance",
      title: "Crisis de vivienda global: Por qué los precios siguen subiendo a pesar de las tasas",
      category: "Sociedad",
      time: "Hace 6 días",
      image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
      url: "https://www.aljazeera.com/economy/",
      desc: "La falta de oferta estructural sigue siendo el principal problema en las grandes capitales mundiales.",
      fullDesc: "Un análisis comparativo entre Londres, Nueva York y Ciudad de México revela que la construcción de vivienda nueva no sigue el ritmo del crecimiento poblacional urbano, manteniendo los precios en niveles de inaccesibilidad récord."
    },
    {
      id: 45,
      symbol: "GOOGL",
      author: "Stock Analysts",
      source: "Zacks",
      title: "Google Cloud supera a Microsoft Azure en crecimiento trimestral",
      category: "Software",
      time: "Hace 1 semana",
      image: "https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?auto=format&fit=crop&w=800&q=80",
      url: "https://www.zacks.com/",
      desc: "La suite de IA Workspace atrae a más empresas del Fortune 500 al ecosistema de Google.",
      fullDesc: "Alphabet ha demostrado que su estrategia de infraestructura de nube está rindiendo frutos. La integración nativa de Gemini en todas sus herramientas profesionales ha sido el factor diferencial para cerrar contratos corporativos multimillonarios."
    },
    {
      id: 46,
      symbol: "PYME",
      author: "Punto de Venta",
      source: "Entrepreneur",
      title: "Digitalización: 7 de cada 10 PYMES mexicanas ya usan WhatsApp para vender",
      category: "Empresas",
      time: "Hace 1 semana",
      image: "https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?auto=format&fit=crop&w=800&q=80",
      url: "https://www.entrepreneur.com/mx/",
      desc: "El e-commerce conversacional se consolida como el motor de los pequeños negocios locales.",
      fullDesc: "WhatsApp Business ha transformado la manera en que los mexicanos compran su despensa y servicios. La facilidad de uso y la cercanía con el cliente son las razones principales de esta adopción masiva en todo el país."
    },
    {
      id: 47,
      symbol: "BIZCOIN",
      author: "Billy",
      source: "BIZEN Labs",
      title: "Bizcoin: Todo lo que necesitas saber sobre la moneda del futuro en BIZEN",
      category: "Plataforma",
      time: "Hace 1 semana",
      image: "https://images.unsplash.com/photo-1622633054716-a218627a718c?auto=format&fit=crop&w=800&q=80",
      url: "#",
      desc: "Descubre cómo ganar más recompensas completando tus lecciones financieras.",
      fullDesc: "Billy explica a detalle el sistema de gamificación de BIZEN. Los Bizcoins no son solo puntos, son una herramienta para practicar cómo gestionar tus activos digitales dentro de un entorno seguro y educativo."
    },
    {
      id: 48,
      symbol: "LOG",
      author: "Supply Chain Pro",
      source: "FreightWaves",
      title: "Desafíos en el Canal de Panamá: La sequía obliga a reducir el tráfico de buques",
      category: "Logística",
      time: "Hace 1 semana",
      image: "https://images.unsplash.com/photo-1544654803-b69110bb81e4?auto=format&fit=crop&w=800&q=80",
      url: "https://www.freightwaves.com/",
      desc: "El comercio global se enfrenta a nuevos cuellos de botella y aumentos de fletes marítimos.",
      fullDesc: "Los bajos niveles de agua en el lago Gatún están impactando una de las arterias más importantes del comercio mundial. Las empresas navieras ya están buscando rutas alternativas, lo que podría elevar los precios de importación en el próximo trimestre."
    },
    {
      id: 49,
      symbol: "ART",
      author: "Culture Beat",
      source: "Vogue Business",
      title: "NFTs 2.0: De la especulación a la utilidad en el mundo del arte físico",
      category: "Estilo de Vida",
      time: "Hace 2 semanas",
      image: "https://images.unsplash.com/photo-1643101809754-43a91784ebec?auto=format&fit=crop&w=800&q=80",
      url: "https://www.voguebusiness.com/",
      desc: "Grandes museos integran certificación por blockchain para garantizar autenticidad.",
      fullDesc: "Tras el estallido de la burbuja especulativa, el mercado ha madurado. Ahora, la tecnología se usa como un pasaporte digital inseparable de las obras físicas, permitiendo un seguimiento real de la procedencia y la propiedad."
    },
    {
      id: 50,
      symbol: "WELLNESS",
      author: "Mindful Living",
      source: "Psychology Today",
      title: "Salud Mental Financiera: El 60% de los Gen-Z sufre estrés por dinero",
      category: "Psicología",
      time: "Hace 2 semanas",
      image: "https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=800&q=80",
      url: "https://www.psychologytoday.com/",
      desc: "Cómo la educación temprana puede reducir la ansiedad relacionada con el ahorro.",
      fullDesc: "Un nuevo estudio revela que la falta de educación financiera es el principal factor de estrés entre los jóvenes. Programas que simplifican conceptos y ofrecen herramientas prácticas son clave para mejorar el bienestar mental de las nuevas generaciones."
    },
    {
      id: 51,
      symbol: "AI",
      author: "Next Horizon",
      source: "Ars Technica",
      title: "Modelos de IA de próxima generación prometen razonamiento autónomo",
      category: "Tecnología",
      time: "Hace 1 hora",
      image: "https://images.unsplash.com/photo-1620712943543-bcc4628c9a00?auto=format&fit=crop&w=800&q=80",
      url: "https://arstechnica.com/",
      desc: "La nueva frontera de la IA ya no es solo imitar el lenguaje, sino resolver problemas lógicos complejos.",
      fullDesc: "Los laboratorios de investigación están reportando avances significativos en la capacidad de los modelos para planificar a largo plazo y corregir sus propios errores en tiempo real, lo que podría desbloquear aplicaciones en ingeniería y medicina nunca antes vistas."
    },
    {
      id: 52,
      symbol: "STOCKS",
      author: "Market Beat",
      source: "Seeking Alpha",
      title: "Empresas de ciberseguridad se disparan tras ola de ataques a infraestructuras",
      category: "Inversión",
      time: "Hace 3 horas",
      image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80",
      url: "https://seekingalpha.com/",
      desc: "El gasto en protección digital se convierte en la máxima prioridad para los CEOs en 2026.",
      fullDesc: "Ante un entorno geopolítico incierto, las corporaciones están moviendo presupuestos masivos hacia la defensa cibernética. Analistas prevén que este sector sea uno de los pocos inmunes a las fluctuaciones de consumo discrecional este año."
    },
    {
      id: 53,
      symbol: "ECONOMY",
      author: "Global Observer",
      source: "Reuters",
      title: "Tasas de interés: ¿Es el 4% la nueva normalidad para la próxima década?",
      category: "Macro",
      time: "Hace 6 horas",
      image: "https://images.unsplash.com/photo-1526628953301-3e589a6a8b74?auto=format&fit=crop&w=800&q=80",
      url: "https://www.reuters.com/business/",
      desc: "Economistas sugieren que la era del dinero gratis ha terminado definitivamente.",
      fullDesc: "Un nuevo consenso entre los directores de bancos centrales sugiere que las presiones demográficas y la transición energética mantendrán el costo del capital por encima de los niveles vistos en la década de 2010. Esto obliga a una reevaluación total de las estrategias de apalancamiento corporativo."
    },
    {
      id: 54,
      symbol: "TAX",
      author: "Legal Today",
      source: "Bloomberg",
      title: "OCDE pacta impuesto global mínimo para corporaciones digitales",
      category: "Gobierno",
      time: "Hace 12 horas",
      image: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=800&q=80",
      url: "https://www.bloomberg.com/politics",
      desc: "La medida busca evitar el traslado de beneficios a paraísos fiscales de forma coordinada.",
      fullDesc: "Más de 130 países han ratificado el acuerdo de un impuesto mínimo del 15% para multinacionales. Se espera que esta reforma histórica genere miles de millones en ingresos adicionales para las haciendas públicas de los países desarrollados y en desarrollo."
    },
    {
      id: 55,
      symbol: "BIZEN",
      author: "Billy Chatbot",
      source: "BIZEN Labs",
      title: "Misiones diarias: Cómo el micro-aprendizaje está cambiando el hábito financiero",
      category: "Educación",
      time: "Hace 15 horas",
      image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80",
      url: "#",
      desc: "Nuestros datos muestran que 5 minutos al día son más efectivos que un seminario de 8 horas.",
      fullDesc: "En BIZEN hemos analizado el comportamiento de miles de usuarios. Aquellos que completan su misión diaria tienen 3 veces más probabilidades de alcanzar su meta de ahorro semestral. La consistencia es el algoritmo definitivo de la libertad."
    }
  ];

  let filtered = ALL_NEWS;
  if (symbol) {
    filtered = ALL_NEWS.filter(n => n.symbol === symbol || n.category === symbol);
    if (filtered.length === 0) {
        filtered = [
            {
                id: 100,
                symbol: symbol,
                author: "Sistema BIZEN",
                source: "Market Analytics",
                title: `${symbol} muestra volatilidad ante reporte de inflación`,
                category: "Mercado",
                time: "Reciente",
                image: "https://images.unsplash.com/photo-1611974717482-48a5c18dc907?auto=format&fit=crop&w=1200",
                url: "#",
                desc: "Los inversores ajustan posiciones esperando los nuevos datos económicos.",
                fullDesc: "La volatilidad actual es un reflejo de la incertidumbre global. Los participantes del mercado están analizando cada dato macroeconómico para prever los movimientos de las tasas de interés."
            },
            ...ALL_NEWS.slice(0, 2)
        ];
    }
  }

  return NextResponse.json(filtered);
}
