import { NextResponse } from 'next/server';

export async function GET(req: Request) {
  const { searchParams } = new URL(req.url);
  const symbol = searchParams.get('symbol');

  const ALL_NEWS = [
    {
      id: 1,
      symbol: "AAPL",
      author: "Analista Senior de Wall Street",
      source: "Bloomberg Finance",
      title: "Apple alcanza valoración récord tras reporte de iPhone",
      category: "Tecnología",
      time: "Hace 2 horas",
      image: "https://images.unsplash.com/photo-1611974715853-2644c59764f1?q=80&w=800&auto=format&fit=crop",
      url: "https://www.bloomberg.com",
      desc: "La empresa de la manzana sobrepasa las expectativas de Wall Street con un crecimiento sólido en servicios.",
      fullDesc: "Apple ha demostrado una vez más por qué es el líder indiscutible en el mercado de consumo electrónico. Con el lanzamiento de su última línea de productos y un enfoque renovado en inteligencia artificial integrada, los servicios de la compañía están escalando a niveles de rentabilidad sin precedentes. Los analistas sugieren que esta tendencia alcista podría mantenerse durante todo el año fiscal."
    },
    {
      id: 2,
      symbol: "TSLA",
      author: "Corresponsal Industrial",
      source: "Reuters Business",
      title: "Tesla anuncia nueva Gigafactory en México",
      category: "Automotriz",
      time: "Hace 4 horas",
      image: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?q=80&w=800&auto=format&fit=crop",
      url: "https://www.reuters.com",
      desc: "Elon Musk confirma la inversión estratégica para la producción de vehículos eléctricos de próxima generación.",
      fullDesc: "La nueva planta de Monterrey se convertirá en el corazón de la producción para el modelo económico de Tesla. Esta decisión estratégica no solo busca optimizar costos logísticos, sino también capitalizar el talento especializado en México. Se estima que la planta generará miles de empleos directos e impulsará el sector de energías limpias en la región."
    },
    {
      id: 3,
      symbol: "BTC",
      author: "Especialista en Activos Digitales",
      source: "CoinDesk Global",
      title: "Bitcoin supera los $70,000 ante adopción institucional",
      category: "Cripto",
      time: "Hace 30 min",
      image: "https://images.unsplash.com/photo-1518546305927-5a555bb7020d?q=80&w=800&auto=format&fit=crop",
      url: "https://www.coindesk.com",
      desc: "El mercado cripto muestra señales de fortaleza con la entrada de grandes fondos de inversión.",
      fullDesc: "El repunte actual de Bitcoin está impulsado por un cambio fundamental en la percepción de los inversores institucionales. Con la aprobación de nuevos ETFs y la integración de soluciones de custodia de grado bancario, la criptomoneda más importante del mundo se está consolidando como el 'oro digital' del siglo XXI, atrayendo capital que antes solo fluía hacia mercados tradicionales."
    },
    {
      id: 4,
      symbol: "RE",
      author: "Experto Inmobiliario",
      source: "Estate Insider",
      title: "Auge en el mercado de Real Estate comercial en Miami",
      category: "Bienes Raíces",
      time: "Hace 5 horas",
      image: "https://images.unsplash.com/photo-1460317442991-0ec239397118?q=80&w=800&auto=format&fit=crop",
      url: "#",
      desc: "Las oficinas de lujo ven una ventaja competitiva en la reubicación de empresas tecnológicas.",
      fullDesc: "Miami se está transformando en el nuevo Silicon Valley del este. El mercado inmobiliario comercial ha visto una absorción récord de metros cuadrados de oficinas Clase A. La combinación de incentivos fiscales y una calidad de vida superior está forzando un rediseño de las estrategias de inversión en Real Estate hacia el sur de la Florida."
    },
    {
      id: 5,
      symbol: "NVDA",
      author: "Analista de Semiconductores",
      source: "TechPulse News",
      title: "NVIDIA domina el mercado de chips para IA",
      category: "Hardware",
      time: "Hace 5 horas",
      image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=800&auto=format&fit=crop",
      url: "#",
      desc: "La demanda de GPUs para entrenamiento de modelos de lenguaje impulsa el valor de mercado.",
      fullDesc: "NVIDIA ha logrado crear un foso tecnológico casi infranqueable. Sus chips H100 se han convertido en el estándar de oro para el desarrollo de Inteligencia Artificial generativa. Mientras competidores intentan alcanzarlos, NVIDIA ya está escalando la producción de su próxima arquitectura, asegurando contratos multimillonarios con los principales proveedores de nube."
    },
    {
      id: 6,
      symbol: "GE",
      author: "Corresponsal de Sustentabilidad",
      source: "Green Echo",
      title: "Inversión masiva en parques eólicos marinos",
      category: "Energía Verde",
      time: "Hace 1 día",
      image: "https://images.unsplash.com/photo-1466611653911-954815391f27?q=80&w=800&auto=format&fit=crop",
      url: "#",
      desc: "Proyectos sustentables a gran escala prometen transformar la matriz energética global.",
      fullDesc: "La transición hacia energías limpias está cobrando una velocidad sin precedentes. Los proyectos de eólica offshore están recibiendo inyecciones de capital tanto públicas como privadas, buscando reducir la dependencia de combustibles fósiles. Estos parques no solo son más eficientes, sino que representan la soberanía energética para el futuro de muchas naciones costeras."
    },
    {
      id: 7,
      symbol: "JPM",
      author: "Economista Principal",
      source: "Financial Insight",
      title: "Tasas de interés se mantienen estables en el trimestre",
      category: "Banca",
      time: "Hace 8 horas",
      image: "https://images.unsplash.com/photo-1501167786227-4cba60f6d58f?q=80&w=800&auto=format&fit=crop",
      url: "#",
      desc: "Las instituciones financieras proyectan un aterrizaje suave para la economía.",
      fullDesc: "La Reserva Federal ha dado señales de una pausa prolongada, lo que ha traído calma a los mercados hipotecarios y corporativos. Aunque la inflación sigue siendo un factor a vigilar, los datos de empleo sugieren que la economía puede soportar tasas más altas por más tiempo sin entrar en una recesión profunda. Los bancos están ajustando sus carteras de crédito en consecuencia."
    },
    {
      id: 8,
      symbol: "GOLD",
      author: "Estratega de Commodities",
      source: "Wealth Report",
      title: "El Oro alcanza máximos históricos como refugio seguro",
      category: "Commodities",
      time: "Hace 3 horas",
      image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?q=80&w=800&auto=format&fit=crop",
      url: "#",
      desc: "La incertidumbre geopolítica impulsa la demanda de activos de reserva de valor.",
      fullDesc: "Históricamente, el oro ha sido el guardián del patrimonio en tiempos de crisis. La escalada de tensiones globales ha forzado a los bancos centrales a aumentar sus reservas de lingotes físicos. Para los inversores individuales, el oro representa una cobertura vital contra la devaluación monetaria y la volatilidad extrema de los mercados de renta variable."
    },
    {
      id: 9,
      symbol: "MXN",
      author: "Estratega Cambiario",
      source: "LatAm Finance",
      title: "El peso mexicano muestra resiliencia frente al dólar",
      category: "Divisas",
      time: "Hace 6 horas",
      image: "https://images.unsplash.com/photo-1512428559083-a400a3b84516?q=80&w=800&auto=format&fit=crop",
      url: "#",
      desc: "El diferencial de tasas sigue favoreciendo a la moneda nacional.",
      fullDesc: "El peso mexicano sigue siendo una de las divisas emergentes más atractivas para el acarreo de divisas (carry trade). La política monetaria prudente del Banco de México, sumada a los flujos récord de remesas y la inversión extranjera directa por el nearshoring, han creado un piso sólido para la moneda nacional frente a las fluctuaciones del billete verde."
    },
    {
      id: 11,
      symbol: "ETH",
      author: "Analista Blockchain",
      source: "Ethereum World",
      title: "Actualización de Ethereum reduce costos de transacción",
      category: "Cripto",
      time: "Hace 10 horas",
      image: "https://images.unsplash.com/photo-1622760219088-90c1576336a1?q=80&w=800&auto=format&fit=crop",
      url: "#",
      desc: "La nueva mejora en la red principal permite una mayor escalabilidad para dApps.",
      fullDesc: "El ecosistema de finanzas descentralizadas (DeFi) ha recibido con entusiasmo la última actualización técnica de Ethereum. Al optimizar el uso del gas, las transacciones diarias se han vuelto más accesibles para el usuario promedio, lo que podría disparar la adopción de contratos inteligentes y NFTs en los próximos meses."
    },
    {
      id: 12,
      symbol: "SPY",
      author: "Gestor de Portafolio",
      source: "ETF Global",
      title: "El S&P 500 alcanza nuevos máximos históricos",
      category: "Bolsa",
      time: "Hace 12 horas",
      image: "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?q=80&w=800&auto=format&fit=crop",
      url: "#",
      desc: "El optimismo corporativo y los resultados tecnológicos impulsan al índice más importante.",
      fullDesc: "A pesar de las preocupaciones externas, las empresas del S&P 500 siguen reportando beneficios robustos. Este rally está liderado por las 'Siete Magníficas', pero se observa una rotación saludable hacia otros sectores como industrial y consumo discrecional, lo que sugiere un mercado alcista con bases más anchas de lo esperado."
    },
    {
      id: 13,
      symbol: "OIL",
      author: "Analista de Energía",
      source: "Global Energy Watch",
      title: "Precios del Crudo suben ante recortes de producción",
      category: "Commodities",
      time: "Hace 14 horas",
      image: "https://images.unsplash.com/photo-1518175006663-1e90b410cda6?q=80&w=800&auto=format&fit=crop",
      url: "#",
      desc: "La OPEP mantiene su postura de restringir la oferta para equilibrar los precios globales.",
      fullDesc: "El mercado del petróleo sigue bajo presión por decisiones estratégicas de los grandes productores. Los recortes voluntarios han logrado mantener el barril por encima de los niveles de soporte fundamentales, impactando directamente en los costos de transporte e inflación a nivel global. Los analistas prevén un mercado ajustado para el resto del trimestre."
    },
    {
      id: 14,
      symbol: "AMZN",
      author: "Corresponsal Ecommerce",
      source: "Market Retail",
      title: "Amazon expande su red de logística con IA",
      category: "Tecnología",
      time: "Hace 18 horas",
      image: "https://images.unsplash.com/photo-1521898284481-a5ec3ad18c72?q=80&w=800&auto=format&fit=crop",
      url: "#",
      desc: "Nuevos algoritmos reducen los tiempos de entrega a menos de 24 horas en regiones clave.",
      fullDesc: "Amazon continúa redefiniendo la logística global mediante la integración profunda de Inteligencia Artificial en sus centros de distribución. La capacidad de predecir la demanda local permite que el inventario esté más cerca del consumidor final, optimizando costos y mejorando drásticamente la satisfacción al cliente."
    },
    {
      id: 15,
      symbol: "MSFT",
      author: "Estratega de Software",
      source: "Enterprise Tech",
      title: "Microsoft Cloud supera proyecciones de ingresos",
      category: "Tecnología",
      time: "Hace 1 día",
      image: "https://images.unsplash.com/photo-1593305841991-05c297ba4575?q=80&w=800&auto=format&fit=crop",
      url: "#",
      desc: "La adopción masiva de Azure AI impulsa la rentabilidad del gigante de Redmond.",
      fullDesc: "Microsoft ha consolidado su posición como la plataforma de nube preferida para la era de la IA. La integración de Copilot en toda su suite de productividad está forzando a las empresas a actualizar sus infraestructuras digitales, generando un flujo de ingresos recurrente que ha sorprendido incluso a los analistas más optimistas."
    },
    {
      id: 16,
      symbol: "META",
      author: "Analista Redes Sociales",
      source: "Social Index",
      title: "Meta anuncia primer dividendo tras año de eficiencia",
      category: "Tecnología",
      time: "Hace 1 día",
      image: "https://images.unsplash.com/photo-1554177255-61502b352de3?q=80&w=800&auto=format&fit=crop",
      url: "#",
      desc: "La reducción de costos y el enfoque en IA dan resultados históricos para Mark Zuckerberg.",
      fullDesc: "Después de un periodo de reestructuración profunda, Meta ha emergido más fuerte que nunca. El anuncio de dividendos es una señal de confianza para los inversores de largo plazo, validando la estrategia de 'Eficiencia' de la compañía. Mientras tanto, sus inversiones en el metaverso comienzan a mostrar casos de uso más prácticos para el sector industrial."
    },
    {
      id: 17,
      symbol: "ABNB",
      author: "Consultor de Turismo",
      source: "Travel Trends",
      title: "Airbnb reporta reservas récord para la temporada baja",
      category: "Bienes Raíces",
      time: "Hace 2 días",
      image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?q=80&w=800&auto=format&fit=crop",
      url: "#",
      desc: "El nomadismo digital sigue impulsando estancias de largo plazo a nivel global.",
      fullDesc: "Airbnb está capitalizando el cambio cultural hacia el trabajo remoto. Las estancias de más de 28 días representan ahora una parte significativa de su negocio, transformando la plataforma de una opción de vacaciones a una solución de vivienda flexible. Esta tendencia está forzando a las ciudades turísticas a repensar su regulación de vivienda a corto plazo."
    },
    {
      id: 18,
      symbol: "SHOP",
      author: "Analista Retail",
      source: "E-Comm Review",
      title: "Shopify fortalece su presencia en el mercado empresarial",
      category: "Tecnología",
      time: "Hace 2 días",
      image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a49d?q=80&w=800&auto=format&fit=crop",
      url: "#",
      desc: "Grandes marcas migran a Shopify Plus buscando mayor rapidez y menor costo operativo.",
      fullDesc: "Shopify está ganando terreno rápidamente ante los gigantes tradicionales de e-commerce empresarial. Su flexibilidad y ecosistema de aplicaciones permiten una innovación mucho más dinámica para las marcas DTC (Direct to Consumer). Con el lanzamiento de nuevas herramientas de checkout optimizado, la tasa de conversión ha mejorado sustancialmente para sus comerciantes."
    },
    {
      id: 19,
      symbol: "ZM",
      author: "Analista de Colaboración",
      source: "Work Future",
      title: "Zoom integra IA generativa para resumen de reuniones",
      category: "Tecnología",
      time: "Hace 3 días",
      image: "https://images.unsplash.com/photo-1588196749597-9ff075ee6b5b?q=80&w=800&auto=format&fit=crop",
      url: "#",
      desc: "La plataforma busca mantenerse relevante en un mercado post-pandemia altamente competitivo.",
      fullDesc: "Ante el regreso parcial a las oficinas, Zoom está evolucionando su suite de productos para convertirse en un hub de colaboración integral. Su nuevo asistente de IA permite a los participantes ponerse al día en tiempo real con resúmenes automáticos, lo que aumenta la productividad y reduce la fatiga de las videollamadas constantes."
    },
    {
      id: 20,
      symbol: "NFLX",
      author: "Corresponsal Entretenimiento",
      source: "Streaming Insider",
      title: "Netflix gana suscriptores tras fin de cuentas compartidas",
      category: "Tecnología",
      time: "Hace 3 días",
      image: "https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?q=80&w=800&auto=format&fit=crop",
      url: "#",
      desc: "La estrategia restrictiva da frutos financieros superando las expectativas iniciales.",
      fullDesc: "Pese a las críticas iniciales en redes sociales, la decisión de Netflix de restringir el uso compartido de cuentas ha demostrado ser un éxito comercial. Millones de usuarios han optado por crear sus propias suscripciones o unirse como miembros adicionales, validando el valor del catálogo de contenido exclusivo de la plataforma frente a una competencia cada vez más fragmentada."
    },
    {
      id: 21,
      symbol: "BABA",
      author: "Estratega de Mercados Emergentes",
      source: "Asia Finance",
      title: "Alibaba se reestructura para impulsar el crecimiento",
      category: "E-commerce",
      time: "Hace 4 horas",
      image: "https://images.unsplash.com/photo-1544654803-b69140b285a1?q=80&w=800&auto=format&fit=crop",
      url: "#",
      desc: "El gigante chino divide su imperio en seis unidades de negocio independientes.",
      fullDesc: "Alibaba ha anunciado una de las reestructuraciones más ambiciosas en su historia. Al dividir sus operaciones en unidades autónomas, busca agilidad operativa y la posibilidad de salidas a bolsa individuales. Los inversores ven esto como una señal positiva de apertura y adaptabilidad ante el panorama regulatorio cambiante de China."
    },
    {
      id: 22,
      symbol: "GOOGL",
      author: "Corresponsal de Innovación",
      source: "AI Frontiers",
      title: "Google DeepMind presenta 'Gemini', su modelo más capaz",
      category: "Tecnología",
      time: "Hace 6 horas",
      image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=800&auto=format&fit=crop",
      url: "#",
      desc: "La nueva frontera de la IA multimodal promete transformar la búsqueda y la productividad.",
      fullDesc: "Google ha dado un golpe sobre la mesa en la carrera de la IA. Gemini no solo procesa texto, sino que entiende y razona sobre imágenes, video y audio de forma nativa. Su integración en el ecosistema de Workspace y búsqueda marca un punto de inflexión en cómo interactuaremos con la tecnología en el corto plazo."
    },
    {
      id: 23,
      symbol: "EUR",
      author: "Macroeconomista",
      source: "Eurozone Review",
      title: "Banco Central Europeo mantiene tipos de interés",
      category: "Banca",
      time: "Hace 8 horas",
      image: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?q=80&w=800&auto=format&fit=crop",
      url: "#",
      desc: "Christine Lagarde advierte que la batalla contra la inflación en Europa no ha terminado.",
      fullDesc: "El BCE ha decidido mantener su postura restrictiva para asegurar el retorno de la inflación al objetivo del 2%. Aunque el crecimiento económico en la eurozona es modesto, la fortaleza del mercado laboral y la persistencia de los precios de servicios sugieren que los recortes de tipos podrían demorarse más de lo previsto por el mercado."
    },
    {
      id: 24,
      symbol: "BTC",
      author: "Investigador Cripto",
      source: "Chain Guard",
      title: "Aumenta el Hashrate global de Bitcoin tras el Halving",
      category: "Cripto",
      time: "Hace 12 horas",
      image: "https://images.unsplash.com/photo-1516245834210-c4c142787335?q=80&w=800&auto=format&fit=crop",
      url: "#",
      desc: "Los mineros despliegan hardware de última generación para mantener la rentabilidad.",
      fullDesc: "A pesar de la reducción en las recompensas de bloque, la red de Bitcoin está más segura que nunca. El despliegue de procesadores ASICs de alta eficiencia energética ha elevado el hashrate a niveles récord. Este fenómeno demuestra la resiliencia del sector minero y la convicción de largo plazo de los operadores industriales."
    },
    {
      id: 25,
      symbol: "COPPER",
      author: "Consultor de Materias Primas",
      source: "Industrial Daily",
      title: "Demanda de Cobre se dispara por vehículos eléctricos",
      category: "Commodities",
      time: "Hace 1 día",
      image: "https://images.unsplash.com/photo-1628155930542-3c7a64e2c833?q=80&w=800&auto=format&fit=crop",
      url: "#",
      desc: "El 'oro rojo' se convierte en el metal crítico para la electrificación global.",
      fullDesc: "Con cada vehículo eléctrico requiriendo hasta cuatro veces más cobre que uno de combustión, el mercado enfrenta un déficit estructural. Los analistas advierten que la falta de nuevas minas operativas podría llevar el precio del cobre a niveles insostenibles en la próxima década si no se acelera la inversión en exploración."
    },
    {
      id: 26,
      symbol: "H2",
      author: "Ingeniero Energético",
      source: "Sustainable Tech",
      title: "Primer hub de Hidrógeno Verde operativo en España",
      category: "Energía Verde",
      time: "Hace 1 día",
      image: "https://images.unsplash.com/photo-1509391366360-2e959784a276?q=80&w=800&auto=format&fit=crop",
      url: "#",
      desc: "La innovación en electrólisis masiva abre camino a la descarbonización industrial.",
      fullDesc: "España se posiciona como el líder europeo en hidrógeno renovable. Al aprovechar su vasta infraestructura solar y eólica, este nuevo hub proveerá energía libre de emisiones a sectores difíciles de electrificar como el acero y el cemento, marcando un hito en la independencia energética de la región."
    },
    {
      id: 27,
      symbol: "VC",
      author: "Analista de Startups",
      source: "Venture Pulse",
      title: "Inversión en Early Stage se recupera a nivel global",
      category: "Venture Capital",
      time: "Hace 2 días",
      image: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?q=80&w=800&auto=format&fit=crop",
      url: "#",
      desc: "Los fondos de capital de riesgo vuelven a apostar por semillas innovadoras en IA y Climatetech.",
      fullDesc: "Tras un periodo de cautela, el 'dry powder' de los fondos de VC está volviendo a fluir hacia emprendedores visionarios. El enfoque actual ha virado desde el crecimiento a toda costa hacia la eficiencia del capital y el desarrollo de tecnologías con propiedad intelectual sólida y barreras de entrada reales."
    },
    {
      id: 28,
      symbol: "BRICS",
      author: "Geopolítico",
      source: "Global Strategist",
      title: "Expansión de los BRICS altera el balance comercial",
      category: "Economía Global",
      time: "Hace 2 días",
      image: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?q=80&w=800&auto=format&fit=crop",
      url: "#",
      desc: "Nuevas adhesiones al bloque buscan alternativas al sistema financiero dominado por el dólar.",
      fullDesc: "La inclusión de potencias regionales en el bloque BRICS está acelerando la discusión sobre una moneda de reserva alternativa o sistemas de pago bilaterales. Este movimiento podría redefinir las rutas comerciales y las alianzas estratégicas en el hemisferio sur para las próximas décadas."
    },
    {
      id: 29,
      symbol: "BANXICO",
      author: "Analista Bancario",
      source: "Mexico Financial",
      title: "Banco de México advierte sobre riesgos inflacionarios",
      category: "Banca",
      time: "Hace 3 días",
      image: "https://images.unsplash.com/photo-1518458022751-0a53d3f96603?q=80&w=800&auto=format&fit=crop",
      url: "#",
      desc: "La junta de gobierno mantiene vigilancia estrecha sobre los precios de alimentos y servicios.",
      fullDesc: "Banxico ha reiterado su compromiso con la estabilidad de precios en México. Pese a la resiliencia económica, factores externos como la volatilidad de materias primas y la presión salarial mantienen la inflación fuera del rango objetivo, lo que sugiere que la tasa de referencia permanecerá elevada por un periodo prolongado."
    },
    {
      id: 30,
      symbol: "AI-ACT",
      author: "Abogado Tecnológico",
      source: "Legal Tech Insight",
      title: "Unión Europea aprueba la primera ley integral de IA",
      category: "Tecnología",
      time: "Hace 3 días",
      image: "https://images.unsplash.com/photo-1589254065878-42c9da997008?q=80&w=800&auto=format&fit=crop",
      url: "#",
      desc: "El marco regulatorio establece límites éticos y técnicos para el uso de modelos avanzados.",
      fullDesc: "La EU AI Act marca un precedente histórico en la gobernanza tecnológica. Al clasificar los sistemas de IA por niveles de riesgo, la legislación busca proteger los derechos fundamentales sin sofocar la innovación. Las empresas ahora deben cumplir con estrictos estándares de transparencia y seguridad para operar en el mercado europeo."
    },
    {
      id: 31,
      symbol: "NFLX",
      author: "Analista Media",
      source: "Streaming Insider",
      title: "Expansión de Netflix en el mercado de videojuegos",
      category: "Tecnología",
      time: "Hace 4 días",
      image: "https://images.unsplash.com/photo-1593305841991-05c297ba4575?q=80&w=800&auto=format&fit=crop",
      url: "#",
      desc: "La plataforma de streaming acelera su apuesta por el gaming interactivo.",
      fullDesc: "Netflix está transformando su oferta de valor de un servicio pasivo a una experiencia interactiva completa. Al incluir juegos basados en sus franquicias más exitosas sin costo adicional, la compañía busca aumentar el tiempo de retención del usuario y diversificar sus fuentes de ingresos a largo plazo."
    },
    {
      id: 32,
      symbol: "CHIP",
      author: "Analista de Supply Chain",
      source: "Logistics Now",
      title: "Crisis de semiconductores llega a su fin",
      category: "Tecnología",
      time: "Hace 4 días",
      image: "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=800&auto=format&fit=crop",
      url: "#",
      desc: "La normalización de la cadena de suministro alivia la presión en el sector automotriz e industrial.",
      fullDesc: "Tras dos años de cuellos de botella extremos, la producción global de microchips se ha equilibrado con la demanda. Esto ha permitido que los fabricantes de automóviles vuelvan a niveles de inventario normales, reduciendo los tiempos de espera y estabilizando los precios en el mercado secundario."
    },
    {
      id: 33,
      symbol: "SPACE",
      author: "Estratega Aeroespacial",
      source: "Orbital Business",
      title: "Minería espacial: el próximo gran mercado de materias primas",
      category: "Futuro",
      time: "Hace 5 días",
      image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=800&auto=format&fit=crop",
      url: "#",
      desc: "Nuevas regulaciones abren la puerta a la explotación de recursos en asteroides cercanos.",
      fullDesc: "Lo que antes era ciencia ficción se está convirtiendo en un plan de negocios tangible. La escasez de tierras raras en la Tierra está impulsando a consorcios privados a desarrollar tecnología de prospección y extracción espacial, con el potencial de redefinir el valor de los metales preciosos en las próximas décadas."
    },
    {
      id: 34,
      symbol: "GENZ",
      author: "Analista de Consumo",
      source: "Market Demographics",
      title: "Generación Z redefine las inversiones de impacto",
      category: "Finanzas",
      time: "Hace 5 días",
      image: "https://images.unsplash.com/photo-1523240715629-66f7d329bc04?q=80&w=800&auto=format&fit=crop",
      url: "#",
      desc: "Los jóvenes inversores priorizan la ética y la sustentabilidad sobre los rendimientos puros.",
      fullDesc: "Un cambio tectónico en la gestión de activos está ocurriendo a medida que la Generación Z entra en su etapa de mayor capacidad de ahorro. Para este grupo, el 'por qué' de una inversión es tan importante como el 'cuánto', lo que está obligando a los fondos tradicionales a integrar criterios ESG de manera auténtica y transparente."
    },
    {
      id: 35,
      symbol: "CYBER",
      author: "Experto en Ciberseguridad",
      source: "Secure World",
      title: "Ataques de Ransomware fuerzan el alza en primas de seguros",
      category: "Ciberseguridad",
      time: "Hace 6 días",
      image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=800&auto=format&fit=crop",
      url: "#",
      desc: "Las empresas incrementan su gasto en resiliencia digital ante amenazas sofisticadas.",
      fullDesc: "La ciberseguridad ya no es un gasto de TI, sino un pilar de la gestión de riesgos corporativos. El aumento de ataques sofisticados contra infraestructuras críticas ha disparado la demanda de seguros contra ciberataques, mientras que las organizaciones invierten millones en sistemas de detección temprana y recuperación de datos."
    }

  ];

  let filtered = ALL_NEWS;
  if (symbol) {
    filtered = ALL_NEWS.filter(n => n.symbol === symbol || n.category === symbol);
    if (filtered.length === 0) {
        filtered = [
            {
                id: 100,
                symbol: symbol,
                author: "Sistema BIZEN",
                source: "Market Analytics",
                title: `${symbol} muestra volatilidad ante reporte de inflación`,
                category: "Mercado",
                time: "Reciente",
                image: "https://images.unsplash.com/photo-1611974715853-2644c59764f1?q=80&w=800&auto=format&fit=crop",
                url: "#",
                desc: "Los inversores ajustan posiciones esperando los nuevos datos económicos.",
                fullDesc: "La volatilidad actual es un reflejo de la incertidumbre global. Los participantes del mercado están analizando cada dato macroeconómico para prever los movimientos de las tasas de interés."
            },
            ...ALL_NEWS.slice(0, 2)
        ];
    }
  }

  return NextResponse.json(filtered);
}
